api/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("ingredients/", views.Ingredient.as_view()),
    path("favorites/", views.Favorites.as_view()),
    path("favorites/<int:recipe_id>/", views.Favorites.as_view()),
    path("subscriptions/", views.Subscribe.as_view()),
    path("subscriptions/<int:author_id>/", views.Subscribe.as_view()),
    path("purchases/", views.Purchase.as_view()),
    path("purchases/<int:recipe_id>/", views.Purchase.as_view()),
]

backend/urls.py
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import include, path
from django.conf.urls import handler404, handler500
from django.conf import settings
from django.conf.urls.static import static


handler404 = "posts.views.page_not_found"  # noqa
handler500 = "posts.views.server_error"  # noqa

urlpatterns = [
    # раздел администратора
    path("admin/", admin.site.urls),
    # flatpages
    path("about/", include("django.contrib.flatpages.urls")),
    # регистрация и авторизация
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    # импорт из приложения posts
    path("api/v1/", include("api.urls")),
    path("", include("posts.urls")),
]

urlpatterns += [
    path("about-us/", views.flatpage, {"url": "/about-us/"}, name="about"),
    path("terms/", views.flatpage, {"url": "/terms/"}, name="terms"),
    path(
        "about-author/", views.flatpage, {"url": "/about-author/"}, name="about-author"
    ),
    path("about-spec/", views.flatpage, {"url": "/about-spec/"}, name="about-spec"),
]

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator

User = get_user_model()


class Tag(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, max_length=100, blank=True, null=True)
    color = models.CharField(max_length=15, blank=True, null=True)

    def __str__(self):
        return self.slug


class Ingredients(models.Model):
    title = models.CharField(max_length=200, null=True, blank=True)
    dimension = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.title


class Recipe(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="recipes")
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to="recipe/", blank=True, null=True)
    description = models.TextField()
    ingredients = models.ManyToManyField(Ingredients, through="RecipeIngredient")
    tags = models.ManyToManyField(Tag)
    cooking_time = models.IntegerField(validators=[MinValueValidator(1)])
    pub_date = models.DateTimeField("date published", auto_now_add=True)

    def __str__(self):
        return self.title


class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name="recipe_ingredients"
    )
    ingredient = models.ForeignKey(
        Ingredients, on_delete=models.CASCADE, related_name="recipes"
    )
    amount = models.IntegerField(default=1)


class ShoppingList(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="user_shopping_list"
    )
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name="recipe_shopping_list"
    )


class FollowUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="follower")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="following")

    def __str__(self):
        return f"follower - {self.user} following - {self.author}"


class FollowRecipe(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="follower_recipe"
    )
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name="follow_recipe"
    )

    def __str__(self):
        return f"follower - {self.user} following recipe- {self.recipe}"

templates/authForm.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Войти на сайт</title>
    <link rel="stylesheet" href="./pages/form.css">
</head>

<body class="body">
    <header class="header">
        {% include 'f/nav.html' %}
    </header>
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">Войти на сайт</h1>
        </div>
        <div class="form-container">
            <form class="form">
                <div class="form__group">
                    <label for="id_username" class="form__label">Имя</label>
                    <div class="form__field-group">
                        <input type="text" name="username" id="id_username" class="form__input">
                        <span class="form__error"></span>
                    </div>
                </div>
                <div class="form__group">
                    <label for="id_password" class="form__label">Пароль</label>
                    <div class="form__field-group">
                        <input type="password" name="password" id="id_password" class="form__input">
                        <span class="form__error">Имя пользователя и пароль не совпадают. Введите правильные
                            данные.</span>
                    </div>
                </div>
                <div class="form__footer">
                    <button class="button button_style_blue">Войти</button>
                    <a class="form__forgot-link">Забыли пароль?</a>
                </div>
            </form>
        </div>


    </main>
    {% include 'f/footer.html' %}
</body>

</html>

templates/authorRecipe.html
<!doctype html>
{% csrf_token %}
{% load static %}
{% load user_filters %}
{% load templates_filters %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Рецепты</title>
    <link rel="stylesheet" href="{% static 'pages/index.css' %}">

</head>

<body class="body">
    <header class="header">
        {% include 'f/nav.html' %}
    </header>
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">{{ username.get_full_name }} </h1>
            <ul class="tags">
                {% for tag in all_tags %}
                <li class="tags__item">
                    <a id="{{ tag.slug }}" class="tags__checkbox tags__checkbox_style_{{ tag.color }}
                                {% if tag.slug in request.GET|get_filter_values %} tags__checkbox_active {% endif %}"
                        href="{% url 'profile' username %}?{{ request|get_filter_link:tag }}"></a>
                    <span class="tags__label">{{ tag.name }}</span>
                </li>
                {% endfor %}
            </ul>

        </div>


        <div class="author-subscribe" data-author="{{ username.id }}">
            {% if user.is_authenticated and not user == username%}
            {% if username|is_follow:user %}
            <button class="button button_style_light-blue button_size_auto" name="subscribe"><span
                    class="icon-check button__icon"></span>Отписаться от автора </button></p>
            {% else %}
            <p style="padding: 0 0 2em 0;"><button class="button button_style_light-blue button_size_auto"
                    name="subscribe" data-out>Подписаться на автора</button></p>
            {% endif %}
            {% endif %}
        </div>
        <div class="card-list">
            {% for post in page %}
            <div class="card" data-id="{{ post.pk }}">
                <a href="{% url 'recipe_view' post.author.username post.id %}" class="link" target="_blank">
                    {% if post.image %}
                    <img src="{{ post.image.url }}"" alt=" {% static '/images/testCardImg.png' %}"
                        class="card__image"></a>
                {% else %}
                <img src="{% static '/images/testCardImg.png' %}"" alt=" Image was broken" class="card__image"></a>
                {% endif %}

                <div class="card__body">
                    <a class="card__title link" href="{% url 'recipe_view' post.author.username post.id %}"
                        target="_blank">{{ post.title }}</a>
                    <ul class="card__items">
                        {% if post.tags %}
                        <ul class="card__items">
                            {% for tag in post.tags.all %}
                            <li class="card__item"><span class="badge badge_style_{{ tag.color }}">{{ tag.name }}</span>
                            </li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </ul>
                    <div class="card__items card__items_column">
                        <p class="card__text"><span class="icon-time"></span> {{ post.cooking_time }} мин.</p>
                        <p class="card__text"><span class="icon-user"></span> <a
                                href="{% url 'profile' post.author.username %}"
                                style="color: black">{{ post.author }}</a></p>
                    </div>
                </div>
                <div class="card__footer">
                    <button class="button button_style_light-blue" name="purchases" data-out><span
                            class="icon-plus button__icon"></span>Добавить в покупки</button>
                    <button class="button button_style_none" name="favorites" data-out><span
                            class="icon-favorite"></span></button>
                </div>
            </div>
            {% endfor %}
        </div>
        {% include 'f/pagination.html' %}
    </main>
    {% include 'f/footer.html' %}
    <script src="{% static 'js/components/MainCards.js' %}"></script>

    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>

    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/AuthorRecipe.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>

    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'authorRecipe.js' %}"></script>
</body>

</html>

templates/base.html
<!doctype html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title%}{% endblock%}</title>
    {% load static %}
    {% csrf_token %}
    {% block static %}
    <link rel="stylesheet" href="{% static 'pages/form.css' %}">
    {% endblock %}
</head>

<body>
    {% include 'f/nav.html' %}
    <main>
        <div class="container">
            {% block content %}
            <!-- Содержимое страницы -->
            {% endblock content %}
        </div>
    </main>
    {% include 'f/footer.html' %}

</body>

</html>

templates/buy_button.html
{% load templates_filters %}

{% if user.is_authenticated %}
{% if recipe|is_shop:user %}
<button class="button button_style_light-blue-outline" name="purchases"><span class="icon-check button__icon"></span>
    Рецепт добавлен</button>
{% else %}
<button class="button button_style_light-blue" name="purchases" data-out><span
        class="icon-plus button__icon"></span>Добавить в покупки</button>
{% endif %}
{% endif %}

templates/favorite.html
<!doctype html>
{% load static %}
{% csrf_token %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Избранное</title>
    <link rel="stylesheet" href="{% static 'pages/index.css' %}">
</head>

<body class="body">
    <header class="header">
        {% include 'f/nav.html' %}
    </header>
    {% load user_filters %}
    {% load templates_filters %}
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">Избранное</h1>
            <ul class="tags">
                {% for tag in all_tags %}
                <li class="tags__item">
                    <a id="{{ tags.slug }}" class="tags__checkbox tags__checkbox_style_{{ tag.color }}
                            {% if tag.slug in request.GET|get_filter_values %} tags__checkbox_active {% endif %}"
                        href="{% url 'favorite' %}?{{ request|get_filter_link:tag }}"></a>
                    <span class="tags__label">{{ tag.name }}</span>
                </li>
                {% endfor %}
            </ul>

        </div>
        <div class="card-list">
            {% for post in page %}
            <div class="card" data-id="{{ post.pk }}">
                <a href="{% url 'recipe_view' post.author.username post.id %}" class="link" target="_blank">
                    {% if post.image %}
                    <img src="{{ post.image.url }}"" alt=" {% static '/images/testCardImg.png' %}"
                        class="card__image"></a>
                {% else %}
                <img src="{% static '/images/testCardImg.png' %}"" alt=" Image was broken" class="card__image"></a>
                {% endif %}

                <div class="card__body">
                    <a class="card__title link" href="{% url 'recipe_view' post.author.username post.id %}"
                        target="_blank">{{ post.title }}</a>
                    <ul class="card__items">

                        {% if post.tags %}
                        <ul class="card__items">
                            {% for tag in post.tags.all %}
                            <li class="card__item"><span class="badge badge_style_{{ tag.color }}">{{ tag.name }}</span>
                            </li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </ul>
                    <div class="card__items card__items_column">
                        <p class="card__text"><span class="icon-time"></span> {{ post.cooking_time }} мин.</p>
                        <p class="card__text"><span class="icon-user"></span> <a
                                href="{% url 'profile' post.author.username %}"
                                style="color: black">{{ post.author }}</a></p>
                    </div>
                </div>
                <div class="card__footer">

                    <button class="button button_style_light-blue" name="purchases" data-out><span
                            class="icon-plus button__icon"></span>Добавить в покупки</button>
                    {% if post|is_favorite:user %}
                    <button class="button button_style_none" name="favorites"><span
                            class="icon-favorite icon-favorite_active"></span></button>
                    {% else %}
                    <button class="button button_style_none" name="favorites" data-out><span
                            class="icon-favorite"></span></button>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
        {% include 'f/pagination.html' %}
        </nav>
    </main>
    {% include 'f/footer.html' %}
    <script src="{% static 'js/components/MainCards.js' %}"></script>

    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>

    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/CardList.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>

    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'favorite.js' %}"></script>
</body>

</html>

templates/formChangeRecipe.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Редактирование рецепта</title>
    <link rel="stylesheet" href="{% static 'pages/index.css' %}">
</head>

<body class="body">
    <header class="header">
        {% include 'f/nav.html' %}
    </header>
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">Редактирование рецепта</h1>
        </div>
        <div class="form-container">
            <form class="form">
                <div class="form__group">
                    <label for="id_name" class="form__label">Название рецепта</label>
                    <div class="form__field-group">
                        <input type="text" id="id_name" name="name" class="form__input">
                        <span class="form__error"></span>
                    </div>
                </div>
                <div class="form__group">
                    <p class="form__label">Теги</p>
                    <div class="form__field-group">
                        <div class="tags">
                            <div class="tags__item">
                                <input type="checkbox" name="breakfast" id="id_breakfast"
                                    class="tags__checkbox tags__checkbox_style_orange">
                                <label for="id_breakfast" class="tags__label">Завтрак</label>
                            </div>
                            <div class="tags__item">
                                <input type="checkbox" name="lunch" id="id_lunch"
                                    class="tags__checkbox tags__checkbox_style_green" checked>
                                <label for="id_lunch" class="tags__label">Обед</label>
                            </div>
                            <div class="tags__item">
                                <input type="checkbox" name="dinner" id="id_dinner"
                                    class="tags__checkbox tags__checkbox_style_purple" checked>
                                <label for="id_dinner" class="tags__label">Ужин</label>
                            </div>
                        </div>
                        <span class="form__error"></span>
                    </div>
                </div>
                <div class="form__group">
                    <label for="nameIngredient" class="form__label">Ингредиенты</label>
                    <div class="form__field-group">
                        <div class="form__field-group-ingredientes">
                            <div class="form__dropdown">
                                <input type="text" id="nameIngredient" class="form__input">
                                <div class="form__dropdown-items"></div>
                            </div>
                            <input type="number" id="cantidad" class="form__input" min="0">
                            <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                        </div>

                        <div class="form__field-group-ingredientes-container">
                            <div class="form__field-item-ingredient" id="ing_3">
                                <span> Оливки 10шт.</span>
                                <span class="form__field-item-delete"></span>
                                <input id="nameIngredient_3" name="nameIngredient_3" type="hidden" value="Оливки">
                                <input id="valueIngredient_3" name="valueIngredient_3" type="hidden" value="10">
                                <input id="unitsIngredient_3" name="unitsIngredient_3" type="hidden" value="шт.">
                            </div>
                            <div class="form__field-item-ingredient" id="ing_2">
                                <span> Картошка 5шт.</span>
                                <span class="form__field-item-delete"></span>
                                <input id="nameIngredient_2" name="nameIngredient_2" type="hidden" value="Картошка">
                                <input id="valueIngredient_2" name="valueIngredient_2" type="hidden" value="5">
                                <input id="unitsIngredient_2" name="unitsIngredient_2" type="hidden" value="шт.">
                            </div>
                        </div>
                        <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                        <span class="form__error"></span>
                    </div>
                </div>
                <div class="form__group">
                    <label for="id_time" class="form__label">Время приготовления</label>
                    <div class="form__field-group form__field-group_time">
                        <input type="text" id="id_time" name="name" class="form__input">
                        <label for="id_time" class="form__label">минут</label>
                        <span class="form__error"></span>
                    </div>
                </div>
                <div class="form__group">
                    <label for="id_description" class="form__label">Описание</label>
                    <div class="form__field-group">
                        <textarea name="description" id="id_description" rows="8" class="form__textarea"></textarea>
                        <span class="form__error"></span>
                    </div>
                </div>
                <div class="form__group">
                    <span class="form__label">Загрузить фото</span>
                    <div class="form__field-group">
                        <label for="id_file" class="form__file-button">Выбрать файл</label>
                        <input type="file" class="form__file" name="file" id="id_file">
                        <span class="form__error"></span>
                    </div>
                </div>
                <div class="form__footer">
                    <button class="button button_style_blue">Сохранить</button> <a style="margin-left: 2.5em" href="#"
                        class="form__ingredient-link">Удалить</a>
                </div>
            </form>
        </div>


    </main>
    {% include 'f/footer.html' %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/utils/debouncing.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'formRecipe.js' %}"></script>
</body>

</html>

templates/formRecipe.html
{% block title %}{% endblock %}
{% block content %}
{% load static %}
{% load user_filters %}
{% csrf_token %}
<html lang="en">

<head>
    {% csrf_token %}
    {% include 'f/nav.html' %}
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Создание рецепта</title>
    <link rel="stylesheet" href="{% static 'pages/form.css' %}">
</head>

<body class="body">
    <header class="header">
        {% csrf_token %}
    </header>
    <main class="main container">
        {% csrf_token %}
        {% load static %}
        {% block static %}
        <link rel="stylesheet" href="{% static 'pages/form.css' %}">
        {% endblock %}
        {% load user_filters %}
        <div class="form-container">
            <form class="form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form__group">
                    <label for="{{ form.title.id_for_label }}" class="form__label">Название рецепта</label>
                    <div class="form__field-group">
                        {{ form.title|addclass:"form__input" }}
                        {% if form.errors %}
                        {% for error in form.title.errors %}
                        <span class="form__error">{{ error|escape }}</span>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="form__group">
                    <p class="form__label">Теги</p>
                    <div class="form__field-group">
                        <div class="tags">
                            <div class="tags__item">
                                {% csrf_token %}
                                {% for tag in all_tags %}
                                <div class="tags__item">
                                    <input type="checkbox" name="tags" value="{{ tag.pk }}" id="id_breakfast"
                                        class="tags__checkbox tags__checkbox_style_{{ tag.color }}">
                                    <label for="id_breakfast" class="tags__label">{{ tag.name }}</label>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        {% if form.errors %}
                        {% for error in form.tags.errors %}
                        <span class="form__error">{{ error|escape }}</span>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="form__group">
                    <label for="nameIngredient" class="form__label">Ингредиенты</label>
                    <div class="form__field-group">
                        <div class="form__field-group-ingredientes">
                            <div class="form__dropdown">
                                <input type="text" id="nameIngredient" class="form__input">
                                <div class="form__dropdown-items"></div>
                            </div>
                            <input type="number" id="cantidad" class="form__input" min="0">
                            <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                        </div>
                        <div class="form__field-group-ingredientes-container"></div>
                        <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                        <span class="form__error">
                            {% if form.non_field_errors %}
                            <div class="non-field-errors">
                                {% for error in form.non_field_errors %}
                                <p class="form-error">{{ error }}</p>
                                {% endfor %}
                            </div>
                            {% endif %}
                        </span>
                    </div>
                </div>
                <div class="form__group">
                    <label for="{{ form.cooking_time.id_for_label }}" class="form__label">Время приготовления</label>
                    <div class="form__field-group form__field-group_time">
                        {{ form.cooking_time|addclass:"form__input" }}
                        <label for="id_time" class="form__label">минут</label>
                        {% if form.errors %}
                        {% for error in field.errors %}
                        <span class="form__error">{{ error|escape }}</span>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="form__group">
                    <label for="{{ form.description.id_for_label }}" class="form__label">Описание</label>
                    <div class="form__field-group">
                        {{ form.description|addclass:"form__textarea" }}
                        {% if form.errors %}
                        {% for error in field.errors %}
                        <span class="form__error">{{ error|escape }}</span>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="form__group">
                    <span class="form__label">Загрузить фото</span>
                    <div class="form__field-group">
                        {{ form.image|addclass:"form__file-button" }}
                        {% if form.errors %}
                        {% for error in field.errors %}
                        <span class="form__error">{{ error|escape }}</span>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="form__footer">
                    {% block form_button %}
                    <button class="button button_style_blue">Создать рецепт</button>
                    {% endblock %}
                </div>
            </form>
        </div>
    </main>
    {% include 'f/footer.html' %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/utils/debouncing.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'formRecipe.js' %}"></script>
</body>

</html>

{% endblock %}

templates/recipe_edit.html
{% extends 'new_recipe.html' %}
{% block title %}{% endblock %}
{% block form_button %}
<button class="button button_style_blue">Сохранить</button> <a style="margin-left: 2.5em"
        href="{% url 'recipe_delete' recipe.id %}" class="form__ingredient-link">Удалить</a>
{% endblock %}